"""marketer disabled by default

Revision ID: 016f0905bc73
Revises: 19bc6af6e16e
Create Date: 2023-06-05 06:33:00.419128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '016f0905bc73'
down_revision = '19bc6af6e16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rate', 'client_types',
               existing_type=postgresql.ARRAY(postgresql.ENUM('company', 'self_employed', 'particular', 'community_owners', name='clienttype')),
               nullable=False)
    op.alter_column('marketer', 'is_active', default=False)
    # ### end Alembic commands #<##


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rate', 'client_types',
               existing_type=postgresql.ARRAY(postgresql.ENUM('company', 'self_employed', 'particular', 'community_owners', name='clienttype')),
               nullable=True)
    op.alter_column('marketer', 'is_active', default=True)
    # ### end Alembic commands ###
