"""role field rename

Revision ID: 0bb5f2a4ca21
Revises: 227432537732
Create Date: 2023-06-13 09:22:31.918755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb5f2a4ca21'
down_revision = '227432537732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('role', sa.String(length=11), nullable=True))
    op.drop_column('user_table', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('user_table', 'role')
    # ### end Alembic commands ###
