"""Update user model fields (is_active, create_at)

Revision ID: 11b8be414502
Revises: 7ee27d833786
Create Date: 2023-01-17 12:08:04.046251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b8be414502'
down_revision = '7ee27d833786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###
