"""units in costs names

Revision ID: 15c84567626a
Revises: 4084864ddc38
Create Date: 2023-08-02 06:56:11.031996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c84567626a'
down_revision = '4084864ddc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data_upgrades()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data_downgrades()
    # ### end Alembic commands ###


def data_upgrades():
    # Add any optional data upgrade migrations here!

    op.execute("UPDATE energy_cost SET concept='IVA (%)' WHERE code = 'iva'")
    op.execute("UPDATE energy_cost SET concept = 'IVA Reducido (%)' WHERE code='iva_reducido'")
    op.execute("UPDATE energy_cost SET concept = 'Impuestos de hidrocarburos (€/kWh)' WHERE code='imp_hidrocarburos'")
    op.execute("UPDATE energy_cost SET concept = 'Impuestos eléctricos (%)' WHERE code='imp_electricos'")


def data_downgrades():
    # Add any optional data downgrade migrations here!

    op.execute("UPDATE energy_cost SET concept = 'IVA' WHERE code='iva'")
    op.execute("UPDATE energy_cost SET concept = 'IVA Reducido' WHERE code='iva_reducido'")
    op.execute("UPDATE energy_cost SET concept = 'Impuestos de hidrocarburos' WHERE code='imp_hidrocarburos'")
    op.execute("UPDATE energy_cost SET concept = 'Impuestos eléctricos' WHERE code='imp_electricos'")
