"""Energy price 1 is not mandatory

Revision ID: 16b272e7f37a
Revises: 447183ed0685
Create Date: 2023-10-02 08:40:58.445799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16b272e7f37a'
down_revision = '447183ed0685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rate', 'energy_price_1',
               existing_type=sa.NUMERIC(precision=14, scale=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rate', 'energy_price_1',
               existing_type=sa.NUMERIC(precision=14, scale=6),
               nullable=False)
    # ### end Alembic commands ###
