"""Minor refactor client and contact

Revision ID: 1ea3d826ae18
Revises: a7e6d78834f2
Create Date: 2023-10-17 08:47:28.985697

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ea3d826ae18"
down_revision = "a7e6d78834f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("client_main_contact_id_fkey", "client", type_="foreignkey")
    op.drop_column("client", "main_contact_id")
    op.add_column("contact", sa.Column("client_id", sa.Integer(), nullable=False))
    op.add_column("contact", sa.Column("is_main_contact", sa.Boolean(), nullable=False))
    op.create_foreign_key(None, "contact", "client", ["client_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contact", type_="foreignkey")
    op.drop_column("contact", "is_main_contact")
    op.drop_column("contact", "client_id")
    op.add_column(
        "client",
        sa.Column("main_contact_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "client_main_contact_id_fkey", "client", "contact", ["main_contact_id"], ["id"]
    )
    # ### end Alembic commands ###
