"""Create Client model

Revision ID: 2204e8f0bbd6
Revises: 16b272e7f37a
Create Date: 2023-10-16 13:35:39.106912

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2204e8f0bbd6"
down_revision = "16b272e7f37a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=False),
        sa.Column(
            "client_type",
            sa.Enum(
                "company",
                "self_employed",
                "particular",
                "community_owners",
                name="clienttypeenum",
            ),
            nullable=False,
        ),
        sa.Column("fiscal_name", sa.String(length=64), nullable=True),
        sa.Column("cif", sa.String(length=9), nullable=True),
        sa.Column("main_contact_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "invoice_notification_type",
            sa.Enum("email", "postal", name="invoicenotificationtype"),
            nullable=False,
        ),
        sa.Column("invoice_email", sa.String(length=256), nullable=True),
        sa.Column("invoice_postal", sa.String(length=256), nullable=True),
        sa.Column("bank_account_holder", sa.String(length=64), nullable=True),
        sa.Column("bank_account_number", sa.String(length=64), nullable=True),
        sa.Column("fiscal_address", sa.String(length=256), nullable=True),
        sa.Column("is_renewable", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["main_contact_id"],
            ["contact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cif"),
    )
    op.create_index(
        op.f("ix_client_fiscal_name"), "client", ["fiscal_name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_client_fiscal_name"), table_name="client")
    op.drop_table("client")
    op.drop_table("contact")
    # ### end Alembic commands ###
