"""margin model

Revision ID: 2318aef2baf1
Revises: 3928406c3e6c
Create Date: 2023-05-14 15:01:48.270607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2318aef2baf1'
down_revision = '3928406c3e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('margin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=13), nullable=False),
    sa.Column('min_consumption', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_consumption', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_margin', sa.Numeric(precision=14, scale=1), nullable=False),
    sa.Column('max_margin', sa.Numeric(precision=14, scale=1), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('margin')
    # ### end Alembic commands ###
