"""client_types_rates

Revision ID: 4be789b5f1cc
Revises: 3eb2b66d5e09
Create Date: 2023-05-24 07:44:15.145082

"""
from alembic import op
import sqlalchemy as sa
from src.infrastructure.sqlalchemy.common import ArrayOfEnum


# revision identifiers, used by Alembic.
revision = "4be789b5f1cc"
down_revision = "3eb2b66d5e09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rate",
        sa.Column(
            "client_types",
            ArrayOfEnum(sa.Enum("company", "self_employed", "particular", "community_owners", name="clienttype")),
            nullable=True,
            default=["particular"],
        ),
    )
    op.execute("UPDATE rate SET client_types = '{particular}'")
    op.drop_column("rate", "client_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rate", sa.Column("client_type", sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_column("rate", "client_types")
    # ### end Alembic commands ###
