"""hist_rate_constraint

Revision ID: 3928406c3e6c
Revises: a9be4f66fd67
Create Date: 2023-05-04 15:07:42.907851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3928406c3e6c'
down_revision = 'a9be4f66fd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'historical_rate', ['price_name', 'price', 'modified_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historical_rate', type_='unique')
    # ### end Alembic commands ###
