"""other costs models

Revision ID: 3eb2b66d5e09
Revises: 2318aef2baf1
Create Date: 2023-05-18 15:28:42.964813

"""
from alembic import op
import sqlalchemy as sa
from src.infrastructure.sqlalchemy.common import ArrayOfEnum

# revision identifiers, used by Alembic.
revision = '3eb2b66d5e09'
down_revision = '2318aef2baf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=124), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('client_types', ArrayOfEnum(sa.Enum('company', 'self_employed', 'particular', 'community_owners', name='clienttype')), nullable=False),
    sa.Column('min_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extra_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('other_costs_rates',
    sa.Column('other_cost_id', sa.Integer(), nullable=True),
    sa.Column('rate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['other_cost_id'], ['other_cost.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], ),
    sa.UniqueConstraint('other_cost_id', 'rate_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('other_costs_rates')
    op.drop_table('other_cost')
    
    # drop enum
    op.execute("DROP TYPE clienttype")
    # ### end Alembic commands ###
