"""fit-saving-studies-to-definition

Revision ID: 403d4e6ce873
Revises: c2fc184c4cd3
Create Date: 2023-06-23 09:56:00.798522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403d4e6ce873'
down_revision = 'c2fc184c4cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_study', sa.Column('client_type', sa.Enum('company', 'self_employed', 'particular', 'community_owners', name='clienttype'), nullable=False))
    op.add_column('saving_study', sa.Column('power_1', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('saving_study', sa.Column('power_2', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('saving_study', sa.Column('power_3', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('saving_study', sa.Column('power_4', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('saving_study', sa.Column('power_5', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('saving_study', sa.Column('power_6', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('saving_study', 'client_name',
               existing_type=sa.VARCHAR(length=124),
               nullable=True)
    op.alter_column('saving_study', 'client_nif',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('saving_study', 'fixed_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=6),
               existing_nullable=True)
    op.drop_column('saving_study', 'client_business_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_study', sa.Column('client_business_name', sa.VARCHAR(length=124), autoincrement=False, nullable=False))
    op.alter_column('saving_study', 'fixed_price',
               existing_type=sa.Numeric(precision=14, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('saving_study', 'client_nif',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('saving_study', 'client_name',
               existing_type=sa.VARCHAR(length=124),
               nullable=False)
    op.drop_column('saving_study', 'power_6')
    op.drop_column('saving_study', 'power_5')
    op.drop_column('saving_study', 'power_4')
    op.drop_column('saving_study', 'power_3')
    op.drop_column('saving_study', 'power_2')
    op.drop_column('saving_study', 'power_1')
    op.drop_column('saving_study', 'client_type')
    # ### end Alembic commands ###
