"""marketers is_active edit

Revision ID: 4105f16ba715
Revises: 71a8ff10266e
Create Date: 2023-03-27 10:27:10.363497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4105f16ba715'
down_revision = '71a8ff10266e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'postal_code',
               existing_type=sa.NUMERIC(precision=8, scale=0),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'postal_code',
               existing_type=sa.String(length=16),
               type_=sa.NUMERIC(precision=8, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
