"""Add roles to user

Revision ID: 447183ed0685
Revises: ded0610fcab2
Create Date: 2023-09-06 16:18:13.651985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447183ed0685'
down_revision = 'ded0610fcab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_table', 'role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_table', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###
