"""energy-cost_concept_unqiue

Revision ID: 4cc52ed7e7f1
Revises: 016f0905bc73
Create Date: 2023-06-05 08:49:03.354247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc52ed7e7f1'
down_revision = '016f0905bc73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE energy_cost SET concept = concept || ' ' || id")
    op.drop_index('ix_energy_cost_concept', table_name='energy_cost')
    op.create_index(op.f('ix_energy_cost_concept'), 'energy_cost', ['concept'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_cost_concept'), table_name='energy_cost')
    op.create_index('ix_energy_cost_concept', 'energy_cost', ['concept'], unique=False)
    # ### end Alembic commands ###
