"""Add other costs fields

Revision ID: 4d0b36c59f17
Revises: 130cba3c95cb
Create Date: 2023-07-12 08:31:24.589919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0b36c59f17'
down_revision = '130cba3c95cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_study', sa.Column('other_cost_kwh', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('saving_study', sa.Column('other_cost_percentage', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('saving_study', sa.Column('other_cost_eur_month', sa.Numeric(precision=14, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saving_study', 'other_cost_eur_month')
    op.drop_column('saving_study', 'other_cost_percentage')
    op.drop_column('saving_study', 'other_cost_kwh')
    # ### end Alembic commands ###
