"""address nullable fields

Revision ID: 5b30d4856fd9
Revises: 0bb5f2a4ca21
Create Date: 2023-06-15 10:24:40.586526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b30d4856fd9'
down_revision = '0bb5f2a4ca21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('address', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('address', 'postal_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('address', 'city',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('address', 'province',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'province',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('address', 'city',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('address', 'postal_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('address', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('address', 'type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
