"""empty message

Revision ID: 6d205345717a
Revises: 4105f16ba715
Create Date: 2023-04-17 13:11:23.631125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d205345717a'
down_revision = '4105f16ba715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price_type', sa.String(length=11), nullable=False),
    sa.Column('energy_type', sa.String(length=11), nullable=False),
    sa.Column('client_type', sa.String(length=16), nullable=False),
    sa.Column('min_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_consumption', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_consumption', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('energy_price_1', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('energy_price_2', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('energy_price_3', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('energy_price_4', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('energy_price_5', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('energy_price_6', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('power_price_1', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('power_price_2', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('power_price_3', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('power_price_4', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('power_price_5', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('power_price_6', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('fixed_term_price', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('rate_type_id', sa.Integer(), nullable=False),
    sa.Column('marketer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marketer_id'], ['marketer.id'], ),
    sa.ForeignKeyConstraint(['rate_type_id'], ['rate_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('historical_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_name', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('rate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_rate')
    op.drop_table('rate')
    # ### end Alembic commands ###
