"""Merketer models

Revision ID: 71a8ff10266e
Revises: b7fd4fc8e494
Create Date: 2023-03-24 11:40:29.068442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a8ff10266e'
down_revision = 'b7fd4fc8e494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('subdivision', sa.String(length=64), nullable=True),
    sa.Column('others', sa.String(length=64), nullable=True),
    sa.Column('postal_code', sa.Numeric(precision=8), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('fiscal_name', sa.String(length=64), nullable=False),
    sa.Column('cif', sa.String(length=9), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('fee', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('max_consume', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('consume_range_datetime', sa.DateTime(), nullable=True),
    sa.Column('surplus_price', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif')
    )
    op.create_index(op.f('ix_marketer_fiscal_name'), 'marketer', ['fiscal_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketer_fiscal_name'), table_name='marketer')
    op.drop_table('marketer')
    op.drop_table('address')
    # ### end Alembic commands ###
