"""EnergyCost is_deleted and user_id modification

Revision ID: 7a96568f4f99
Revises: dd0cb128d52d
Create Date: 2023-02-06 14:28:11.819515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a96568f4f99'
down_revision = 'dd0cb128d52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_costs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('energy_costs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('energy_costs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('energy_costs', 'is_deleted')
    # ### end Alembic commands ###
