"""Add rate details fields to suggested rate

Revision ID: 7ff7c00b9e73
Revises: ae852e953e99
Create Date: 2023-07-24 07:53:07.944877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff7c00b9e73'
down_revision = 'ae852e953e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_rate', sa.Column('energy_price_1', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('energy_price_2', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('energy_price_3', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('energy_price_4', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('energy_price_5', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('energy_price_6', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('power_price_1', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('power_price_2', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('power_price_3', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('power_price_4', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('power_price_5', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('power_price_6', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('fixed_term_price', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('suggested_rate', sa.Column('price_type', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_rate', 'price_type')
    op.drop_column('suggested_rate', 'fixed_term_price')
    op.drop_column('suggested_rate', 'power_price_6')
    op.drop_column('suggested_rate', 'power_price_5')
    op.drop_column('suggested_rate', 'power_price_4')
    op.drop_column('suggested_rate', 'power_price_3')
    op.drop_column('suggested_rate', 'power_price_2')
    op.drop_column('suggested_rate', 'power_price_1')
    op.drop_column('suggested_rate', 'energy_price_6')
    op.drop_column('suggested_rate', 'energy_price_5')
    op.drop_column('suggested_rate', 'energy_price_4')
    op.drop_column('suggested_rate', 'energy_price_3')
    op.drop_column('suggested_rate', 'energy_price_2')
    op.drop_column('suggested_rate', 'energy_price_1')
    # ### end Alembic commands ###
