"""add_user_delete_at

Revision ID: 90d920143e2a
Revises: f93dd6691f53
Create Date: 2023-03-06 11:16:53.658270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d920143e2a'
down_revision = 'f93dd6691f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'deleted_at')
    # ### end Alembic commands ###
