"""Add token column

Revision ID: 96c61ba27c52
Revises: 053cdd4775d4
Create Date: 2023-01-10 10:45:03.009677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c61ba27c52'
down_revision = '053cdd4775d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'token')
    # ### end Alembic commands ###
