"""new fields Rate model

Revision ID: a9be4f66fd67
Revises: d9a5f2b04af5
Create Date: 2023-04-26 06:20:03.154620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9be4f66fd67'
down_revision = 'd9a5f2b04af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate', sa.Column('permanency', sa.Boolean(), nullable=False))
    op.add_column('rate', sa.Column('length', sa.Integer(), nullable=False))
    op.add_column('rate', sa.Column('is_full_renewable', sa.Boolean(), nullable=True))
    op.add_column('rate', sa.Column('compensation_surplus', sa.Boolean(), nullable=True))
    op.add_column('rate', sa.Column('compensation_surplus_value', sa.Numeric(precision=14, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate', 'compensation_surplus_value')
    op.drop_column('rate', 'compensation_surplus')
    op.drop_column('rate', 'is_full_renewable')
    op.drop_column('rate', 'length')
    op.drop_column('rate', 'permanency')
    # ### end Alembic commands ###
