"""Add costs columns to saving study

Revision ID: ae852e953e99
Revises: c9b8b569ec6c
Create Date: 2023-07-20 11:45:54.265488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae852e953e99'
down_revision = 'df42daf46f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_rate', sa.Column('energy_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('suggested_rate', sa.Column('power_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('suggested_rate', sa.Column('fixed_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('suggested_rate', sa.Column('other_costs', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('suggested_rate', sa.Column('ie_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('suggested_rate', sa.Column('ih_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('suggested_rate', sa.Column('iva_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_rate', 'iva_cost')
    op.drop_column('suggested_rate', 'ih_cost')
    op.drop_column('suggested_rate', 'ie_cost')
    op.drop_column('suggested_rate', 'other_costs')
    op.drop_column('suggested_rate', 'fixed_cost')
    op.drop_column('suggested_rate', 'power_cost')
    op.drop_column('suggested_rate', 'energy_cost')
    # ### end Alembic commands ###
