"""Create saving studies models

Revision ID: c2fc184c4cd3
Revises: 5b30d4856fd9
Create Date: 2023-06-22 09:24:44.616603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fc184c4cd3'
down_revision = '5b30d4856fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saving_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('user_creator_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='savingstudystatusenum'), nullable=False),
    sa.Column('cups', sa.String(length=124), nullable=False),
    sa.Column('analyzed_days', sa.Integer(), nullable=False),
    sa.Column('current_rate_type_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=124), nullable=False),
    sa.Column('client_business_name', sa.String(length=124), nullable=False),
    sa.Column('client_nif', sa.String(length=10), nullable=False),
    sa.Column('consumption_p1', sa.Integer(), nullable=True),
    sa.Column('consumption_p2', sa.Integer(), nullable=True),
    sa.Column('consumption_p3', sa.Integer(), nullable=True),
    sa.Column('consumption_p4', sa.Integer(), nullable=True),
    sa.Column('consumption_p5', sa.Integer(), nullable=True),
    sa.Column('consumption_p6', sa.Integer(), nullable=True),
    sa.Column('annual_consumption', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_marketer', sa.String(length=124), nullable=True),
    sa.Column('power_price_1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('power_price_2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('power_price_3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('power_price_4', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('power_price_5', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('power_price_6', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('energy_price_1', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('energy_price_2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('energy_price_3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('energy_price_4', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('energy_price_5', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('energy_price_6', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fixed_price_type', sa.Enum('EURO_MONTH', 'EURO_KWH', 'PERCENTAGE', name='savingstudyclientfixedpriceenum'), nullable=True),
    sa.Column('fixed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['current_rate_type_id'], ['rate_type.id'], ),
    sa.ForeignKeyConstraint(['user_creator_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggested_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('saving_study_id', sa.Integer(), nullable=False),
    sa.Column('marketer_name', sa.String(length=124), nullable=False),
    sa.Column('has_contractual_commitment', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('rate_name', sa.String(length=124), nullable=False),
    sa.Column('renewable', sa.Boolean(), nullable=False),
    sa.Column('net_metering', sa.Boolean(), nullable=False),
    sa.Column('surplus_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applied_profit_margin', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('final_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('theoretical_commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('saving_relative', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('saving_absolute', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['saving_study_id'], ['saving_study.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_rate')
    op.drop_table('saving_study')
    
    # drop enum
    op.execute("DROP TYPE savingstudystatusenum")
    op.execute("DROP TYPE savingstudyclientfixedpriceenum")
    # ### end Alembic commands ###
