"""Remove fixed_price_type field from saving study

Revision ID: c9b8b569ec6c
Revises: 4d0b36c59f17
Create Date: 2023-07-12 10:14:11.908020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9b8b569ec6c'
down_revision = '4d0b36c59f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saving_study', 'fixed_price_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_study', sa.Column('fixed_price_type', postgresql.ENUM('EURO_MONTH', 'EURO_KWH', 'PERCENTAGE', name='savingstudyclientfixedpriceenum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
