"""energy costs model

Revision ID: dd0cb128d52d
Revises: 0731518a9184
Create Date: 2023-02-02 10:28:28.705278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0cb128d52d'
down_revision = '0731518a9184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=124), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_costs_concept'), 'energy_costs', ['concept'], unique=False)
    op.create_index(op.f('ix_energy_costs_id'), 'energy_costs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_costs_id'), table_name='energy_costs')
    op.drop_index(op.f('ix_energy_costs_concept'), table_name='energy_costs')
    op.drop_table('energy_costs')
    # ### end Alembic commands ###
