"""Update decimals in min_margin and max_margin fields

Revision ID: ded0610fcab2
Revises: 15c84567626a
Create Date: 2023-08-17 09:27:18.000254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded0610fcab2'
down_revision = '15c84567626a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('margin', 'min_margin',
               existing_type=sa.NUMERIC(precision=14, scale=1),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    op.alter_column('margin', 'max_margin',
               existing_type=sa.NUMERIC(precision=14, scale=1),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('margin', 'max_margin',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=14, scale=1),
               existing_nullable=False)
    op.alter_column('margin', 'min_margin',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=14, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###
