"""name field energy cost

Revision ID: df42daf46f27
Revises: c9b8b569ec6c
Create Date: 2023-07-17 08:49:50.769395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df42daf46f27'
down_revision = 'c9b8b569ec6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_cost', sa.Column('code', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'energy_cost', ['code'])
    data_upgrades()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'energy_cost', type_='unique')
    op.drop_column('energy_cost', 'code')
    # ### end Alembic commands ###


def data_upgrades():
    # Add any optional data upgrade migrations here!

    op.execute("UPDATE energy_cost SET code='iva' WHERE concept = 'IVA'")
    op.execute("UPDATE energy_cost SET code='iva_reducido' WHERE concept = 'IVA Reducido'")
    op.execute("UPDATE energy_cost SET code='imp_hidrocarburos' WHERE concept = 'Impuestos de hidrocarburos'")
    op.execute("UPDATE energy_cost SET code='imp_electricos' WHERE concept = 'Impuestos eléctricos'")
