"""Remove default data and add superadmin

Revision ID: f93dd6691f53
Revises: bcd7c4048d8a
Create Date: 2023-03-01 13:41:29.235982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Integer, Numeric, String, Boolean
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = 'f93dd6691f53'
down_revision = 'bcd7c4048d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('is_superadmin', sa.Boolean(), nullable=False, server_default=sa.text('False')))
    data_upgrades()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data_downgrades()
    op.drop_column('user_table', 'is_superadmin')
    # ### end Alembic commands ###

def data_upgrades():
    # Add any optional data upgrade migrations here!

    op.execute("delete from energy_cost where concept in ('Iva', 'Iva Redcido', 'Impuestos de hidrocarburos', 'Impuestos eléctricos')")

def data_downgrades():
    # Add any optional data downgrade migrations here!

    energy_costs = table('energy_cost',
        column('concept', String),
        column('amount', Numeric(14,6)),
        column('user_id', Integer),
        column('is_active', Boolean),
    )

    op.bulk_insert(energy_costs,
        [
            {'concept': 'Iva', 'amount': 21, 'user_id': None, 'is_active': True},
            {'concept': 'Iva Redcido', 'amount': 5, 'user_id': None, 'is_active': True},
            {'concept': 'Impuestos de hidrocarburos', 'amount': 0.00234, 'user_id': None, 'is_active': True},
            {'concept': 'Impuestos eléctricos', 'amount': 5.1127, 'user_id': None, 'is_active': True},
        ]
    )    