"""add responsible field

Revision ID: fb49ea518ae6
Revises: 11b8be414502
Create Date: 2023-01-26 06:55:35.408538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb49ea518ae6'
down_revision = '11b8be414502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('responsible_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['responsible_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'responsible_id')
    # ### end Alembic commands ###
