"""Add rate type model

Revision ID: fde3d62c8401
Revises: 11b8be414502
Create Date: 2023-01-24 13:35:28.626579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde3d62c8401'
down_revision = '11b8be414502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('energy_type', sa.String(length=16), nullable=False),
    sa.Column('max_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_types_energy_type'), 'rate_types', ['energy_type'], unique=False)
    op.create_index(op.f('ix_rate_types_id'), 'rate_types', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_types_id'), table_name='rate_types')
    op.drop_index(op.f('ix_rate_types_energy_type'), table_name='rate_types')
    op.drop_table('rate_types')
    # ### end Alembic commands ###
